name: Publish @filen/utils to NPM

on:
  release:
    types: [published]

concurrency:
  group: 'npm-publish-utils'
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains(github.event.release.tag_name, '@filen/utils') || contains(github.event.release.name, '@filen/utils')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install dependencies
        working-directory: packages/filen-utils
        run: npm install --package-lock-only && npm ci
      - name: Build
        working-directory: packages/filen-utils
        run: npm run build
      - name: Configure npm for publishing
        working-directory: packages/filen-utils
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > ~/.npmrc
      - name: Publish
        working-directory: packages/filen-utils
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: Cleanup
        working-directory: packages/filen-utils
        run: rm -rf ~/.npmrc
